### PR TITLE
feat : Add themes and custom quotes

### PR DESCRIPTION
**Pull request by reskimulud**
I added two themes namely `algolia` and `monokai`. I also added a feature to customize quotes by adding a query `myquote` by the user

### CODE REVIEW

**Comment by PiyushSuthar** [comment]
Great! Can you add info about this in README?

**Comment by reskimulud** [comment]
oke sure

**Comment by reskimulud** [comment]
oke done @PiyushSuthar

**Comment by PiyushSuthar** [comment]
Looks good to me, Thanks for the contribution 🎉

**Pull request merged**
