### PR TITLE
added theme: graywhite

### PR DESCRIPTION
**Pull request by krakxn**
The PR adds a new theme (`graywhite`).

### CODE REVIEW

**Review by PiyushSuthar — CHANGES_REQUESTED** [review]
Please format this correctly

**Review by krakxn — COMMENTED** [review]
Do you mean this line? 

```
background": 'F0F1F2',
```

**Comment by janaSunrise** [comment]
Hey there! Please pull the typescript codebase, and use prettier formatting before pushing 😁 sorry for the inconvenience!

**Comment by krakxn** [comment]
@janaSunrise The former is not necessary, as the forked repo does include it. As for the latter, I will make a new PR instead (formatted w/ prettier); I will tag both of you there.

**Pull request closed without merging**
